### PR TITLE
fix: capitalization of termux-setup-storage

### PR DESCRIPTION
**Pull request by 2096779623**
Before fixing:

image

Fixed:

image

(Via build)

### CODE REVIEW

**Comment by rihaq** [comment]
@2096779623 how did you made termux background like that?

**Comment by metafates** [comment]
oh, right! thanks for noticing

**Comment by metafates** [comment]
Looks like you are packaging mangal for termux, thank you! I'll merge it into the main soon (I hope). Need to finish some other stuff before it

**Comment by 2096779623** [comment]
> @2096779623 how did you made termux background like that?

Just a ssh client on windows.

**Pull request merged**
